# Generated by Django 4.2.5 on 2023-09-05 15:16
import citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", citext.fields.CITextField()),
                ("char", citext.fields.CICharField(max_length=255)),
                ("email", citext.fields.CIEmailField(max_length=254)),
            ],
        ),
    ]
